name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: sonatype-nexus-staging # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: CI_DEPLOY_USERNAME # env variable for username in deploy
          server-password: CI_DEPLOY_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: CI_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Install, unit test, integration test
        run: mvn install -Dmaven.javadoc.skip=true -B -V

      - name: Release to maven central
        if: github.ref_name == 'master' && github.event_name != 'pull_request' && github.repository == 'swisspost/kobuka'
        run: |
          curl -s get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 3.0.8
          
          chmod +x ./maybe-release.sh
          ./maybe-release.sh
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}

      - name: After release
        run: bash <(curl -s https://codecov.io/bash)
